### ISSUE TITLE
怎么让同一水平线上出现3个或多个，目前你这项目中只有两个，求回复

### ISSUE THREAD

**Issue by andi911** [cjq002/UICollectionView-Pure-code#1]

**Comment by CarrySniper** [comment]
你可以查看我的代码
在ViewController.m文件120行或者方法:
- (CGSize)collectionView:(UICollectionView _)collectionView layout:(UICollectionViewLayout_)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath *)indexPath内。

return CGSizeMake((fDeviceWidth-20)/2, (fDeviceWidth-20)/2+50);

CGSize是宽高，自己定义大小的。可以把除以2改为处以3或者其他多个。由于我的CollectionViewCell是自动适配大小的，所以可以直接修改运行且正常显示。

**Comment by andi911** [comment]
你看下这个网址中的一行出现的三个，https://github.com/TopicSo/RAMCollectionViewFlemishBondLayout，他实现的有点复杂，有没有更简单的实现

**Comment by CarrySniper** [comment]
应该只能这样了吧，系统自带的只有这种格式的了。要想改掉系统的只有重新方法或添加协议委托代理修改。不然就用scrollView或tableView代替试试咯。他这里主要的是RAMCollectionViewFlemishBondLayout封装类而已，只有复制他这个类文件就可以使用了，也不算复杂。

这个是他的调用协议方法
- (RAMCollectionViewFlemishBondLayoutGroupDirection)collectionView:(UICollectionView *)collectionView layout:(RAMCollectionViewFlemishBondLayout *)collectionViewLayout highlightedCellDirectionForGroup:(NSInteger)group atIndexPath:(NSIndexPath *)indexPath
  {
  RAMCollectionViewFlemishBondLayoutGroupDirection direction;
  
  if (indexPath.row % 2) {
      direction = RAMCollectionViewFlemishBondLayoutGroupDirectionRight;
  } else {
      direction = RAMCollectionViewFlemishBondLayoutGroupDirectionLeft;
  }
  
  return direction;
  }

**Comment by andi911** [comment]
能给个qq号吗，有个问题想请教下

**Comment by CarrySniper** [comment]
qq:2082142540 呵呵，也是菜鸟一个 谈不上请教
